### ISSUE TITLE
Enter error

### ISSUE THREAD

**Issue by webdewduck** [trngl8/library-project#225]
an internal server error on new username
```
  File "/home/duck/library-project/index.py", line 51, in home
    library.get_repository('users').add({
  File "/home/duck/library-project/library.py", line 139, in add
    item_id = self.storage.add_line(self.name, item)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duck/library-project/storage.py", line 90, in add_line
    line = str(new_id) + "," + ",".join(item.values())
                               ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 2: expected str instance, type found
```

**Comment by webdewduck** [comment]
test failed 

```
FAIL: test_home_set_username (test_index.AppTestCase.test_home_set_username)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/duck/library-project/test_index.py", line 28, in test_home_set_username
    self.assertEqual(response.status_code, 302)
AssertionError: 500 != 302
```
